message("Installing / updating HybridCheck and required packages")
chooseCRANmirror(ind = 83)
update.packages(ask=FALSE)
library(devtools)

pkg <- c('devtools', 'shiny', 'ggplot2', 'grid', 'gridExtra', 'ape', 'png')
install.packages(pkg)
source('http://bioconductor.org/biocLite.R')
biocLite('Biostrings', ask = F)
biocLite('IRanges', ask = F)
install_github("Ward9250/HybridCheck", build_vignettes = TRUE)
