---
layout: manualsection
title: Testing and dating detected blocks
permalink: 08-manual.html
manual: true
published: false
status: process
---

```{r include=FALSE, echo=FALSE}
FirstGroup <- c("Seq1", "Seq2", "Seq3")
SecondGroup <- c("Seq4", "Seq5", "Seq6")
ThirdGroup <- c("Seq7", "Seq8", "Seq9", "Seq10")
myGroups <- list(FirstGroup, SecondGroup, ThirdGroup) # Put the groups in a list.
MyAnalysis$setParameters("TripletGeneration", Groups = myGroups, PartitionStrictness = 1L)
tripletsToScan <- list(c("Seq1", "Seq4", "Seq7"), c("Seq1", "Seq4", "Seq8"))
MyAnalysis$analyzeSS(tripletsToScan)
MyAnalysis$findBlocks(list(c("Seq1", "Seq4", "Seq7"), c("Seq1", "Seq4", "Seq8")))
```

Having searched for blocks in the desired sequence triplets, the `BlockDating` step is executed using the `dateBlocks` method.

This step assigns a significance value to blocks based on the size of a block, the number of mutations observed, and the binomial probability distribution.

The parameters for this step are:

MutationRate
  : The substitution rate assumed when estimating the ages of blocks. By default it is 10e-9.

PValue
  : The critical alpha value when testing the significance values of blocks. By default is is 0.05.
  
BonfCorrection
  : Logical (`TRUE` / `FALSE`) when `TRUE` (default) the `PValue` will be adjusted with a Bonferroni correction.
  
DateAnyway
  : Logical (`TRUE` / `FALSE`) when `TRUE` (`FALSE` by default), all detected blocks will be kept and dated.
  : When `FALSE`, blocks that do not pass the critical alpha when testing for significance are not kept in the results
  : and are not dated.
  
  





