# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sequenceChecker_cpp <- function(x) {
    .Call('HybRIDS_sequenceChecker_cpp', PACKAGE = 'HybRIDS', x)
}

